### ISSUE TITLE
Fails to build with glibc-2.27.9000

### ISSUE THREAD

**Issue by opoplawski** [ge-ne/bibtool#47]
Fails to build with latest glibc:
```
rewrite.c: In function 'get_regex_syntax':
rewrite.c:1351:5: error: duplicate case value
     case RE_SYNTAX_POSIX_EGREP: return "posix_egrep";/*                      */
     ^~~~
rewrite.c:1349:5: note: previously used here
     case RE_SYNTAX_EGREP:       return "egrep";    /*                        */
     ^~~~
```
These are now the same, regex.h has:
```
# define RE_SYNTAX_EGREP                                                \
  ((RE_SYNTAX_POSIX_EXTENDED | RE_INVALID_INTERVAL_ORD | RE_NEWLINE_ALT) \
   & ~(RE_CONTEXT_INVALID_OPS | RE_DOT_NOT_NULL))

/* POSIX grep -E behavior is no longer incompatible with GNU.  */
# define RE_SYNTAX_POSIX_EGREP                                          \
  RE_SYNTAX_EGREP
```
Not sure the best way to handle this.

**Comment by ge-ne** [comment]
solved by CPP
